pipeline {
    agent any
    environment{
        FULL_IMAGE = "854108365735.dkr.ecr.us-west-1.amazonaws.com/ies/django-qa:${VERSION}"
        TASK_DEFINITION =""
        NEW_TASK_DEFINITION=""
        NEW_TASK_INFO=""
        NEW_REVISION=""
        TASK_FAMILY="ies-qa"
    }
    stages {
        stage('Checkout using tag') {
            steps{
                checkout([
                    $class: 'GitSCM', 
                    branches: [[name: 'refs/tags/${VERSION}']], 
                    doGenerateSubmoduleConfigurations: false, 
                    extensions: [], 
                    submoduleCfg: [], 
                    userRemoteConfigs: [[url: 'git@bitbucket.org:nal-solutions/ies-admin-be.git', credentialsId: 'bitbucket-credential']]
                ])
            }

        }
        stage('Build') {
            when {
                expression {
                    def action=env.ACTION 
                    return action == 'BuildAndDeploy' || action == 'OnlyBuild'
                }
            }
            steps {
                
                sh 'docker build -t nginx-repo -f docker/Dockerfile-nginx:${VERSION} ./docker'
                sh 'docker build -t django-repo -f docker/Dockerfile-django:${VERSION} .
'
            }
        }
        stage('Upload image to ECR') {
            when { 
                expression {
                    def action=env.ACTION 
                    return action == 'BuildAndDeploy' || action == 'OnlyBuild'
                }
            }
            steps {
                sh 'aws ecr get-login-password --region us-west-1 | docker login --username AWS --password-stdin 854108365735.dkr.ecr.us-west-1.amazonaws.com'

                sh 'docker tag nginx-repo:${VERSION} 854108365735.dkr.ecr.us-west-1.amazonaws.com/ies/nginx-qa:${VERSION}'
                
                sh 'docker push 854108365735.dkr.ecr.us-west-1.amazonaws.com/ies/nginx-qa:${VERSION}'

                 sh 'docker tag  django-repo:${VERSION} 854108365735.dkr.ecr.us-west-1.amazonaws.com/ies/django-qa:${VERSION}'
                
                sh 'docker push 854108365735.dkr.ecr.us-west-1.amazonaws.com/ies/django-qa:${VERSION}'
            }
        }
        
        stage('Update task definition and force deploy ecs service') {
            when {
                expression {
                    def action=env.ACTION 
                    return action == 'BuildAndDeploy' || action == 'OnlyDeploy'
                }
            }
            steps {
                sh '''
                    TASK_DEFINITION=$(aws ecs describe-task-definition --task-definition ${TASK_FAMILY} --region "us-west-1")
                    NEW_TASK_DEFINITION=$(echo $TASK_DEFINITION | jq --arg IMAGE "${FULL_IMAGE}" '.taskDefinition | .containerDefinitions[0].image = $IMAGE | del(.taskDefinitionArn) | del(.revision) | del(.status) | del(.requiresAttributes) | del(.compatibilities) |  del(.registeredAt)  | del(.registeredBy)')
                    NEW_TASK_INFO=$(aws ecs register-task-definition --region "us-west-1" --cli-input-json "$NEW_TASK_DEFINITION")
                    NEW_REVISION=$(echo $NEW_TASK_INFO | jq '.taskDefinition.revision')
                    aws ecs update-service --cluster cicd-ies --service ies-admin-qa --task-definition ${TASK_FAMILY}:${NEW_REVISION} --force-new-deployment
                '''
     
            }
        }
    }
}
